In [7]:
#imports
import pandas as pd
import time
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)
from background_functions import logdiffexp, G2G_varying_LL, G2G_varying_MLE, G2G_varying_optim

In [8]:
#read in the data 
kb = pd.read_csv('~/Downloads/kb_covars.csv')

In [9]:
last_instance_index = kb.groupby('id').tail(1).index

# Initialize event column
kb['Event'] = 0

# Create the event column
kb.loc[last_instance_index, 'Event'] = kb.loc[last_instance_index, 'censor'].apply(lambda x: 1 if x == 0 else 0)

kb2  = kb.copy()

# print df
kb.head(10)

   id  week  num_weeks  censor  coupon   anyp  Event
0   1     1          1       0     0.0  55.61      1
1   2     1          1       0     0.0  55.61      1
2   3     1          1       0     0.0  55.61      1
3   4     1          1       0     0.0  55.61      1
4   5     1          1       0     0.0  55.61      1
5   6     1          1       0     0.0  55.61      1
6   7     1          1       0     0.0  55.61      1
7   8     1          1       0     0.0  55.61      1
8   9     1          2       0     0.0  55.61      0
9   9     2          2       0     0.0  55.82      1

In [10]:
#data manipulation steps
# Data manipulation
id_df = kb.groupby('id')['censor'].max().reset_index()

kb2 = kb2.drop(columns=['censor']).merge(id_df, on='id', how='inner')

kb2['status'] = (kb2['censor'] + 1) % 2

display(kb2.head(50))
print(kb2['status'].min())

    id  week  num_weeks    coupon   anyp  Event  censor  status
0    1     1          1  0.000000  55.61      1       0       1
1    2     1          1  0.000000  55.61      1       0       1
2    3     1          1  0.000000  55.61      1       0       1
3    4     1          1  0.000000  55.61      1       0       1
4    5     1          1  0.000000  55.61      1       0       1
5    6     1          1  0.000000  55.61      1       0       1
6    7     1          1  0.000000  55.61      1       0       1
7    8     1          1  0.000000  55.61      1       0       1
8    9     1          2  0.000000  55.61      0       0       1
9    9     2          2  0.000000  55.82      1       0       1
10  10     1          2  0.000000  55.61      0       0       1
11  10     2          2  0.000000  55.82      1       0       1
12  11     1          2  0.000000  55.61      0       0       1
13  11     2          2  0.000000  55.82      1       0       1
14  12     1          2  0.000000  55.61      0       0       1
15  12     2          2  0.000000  55.82      1       0       1
16  13     1          2  0.000000  55.61      0       0       1
17  13     2          2  0.000000  55.82      1       0       1
18  14     1          2  0.000000  55.61      0       0       1
19  14     2          2  0.000000  55.82      1       0       1
20  15     1          3  0.000000  55.61      0       0       1
21  15     2          3  0.000000  55.82      0       0       1
22  15     3          3  0.018037  55.65      1       0       1
23  16     1          3  0.000000  55.61      0       0       1
24  16     2          3  0.000000  55.82      0       0       1
25  16     3          3  0.018037  55.65      1       0       1
26  17     1          4  0.000000  55.61      0       0       1
27  17     2          4  0.000000  55.82      0       0       1
28  17     3          4  0.018037  55.65      0       0       1
29  17     4          4  0.126259  81.17      1       0       1
30  18     1          4  0.000000  55.61      0       0       1
31  18     2          4  0.000000  55.82      0       0       1
32  18     3          4  0.018037  55.65      0       0       1
33  18     4          4  0.126259  81.17      1       0       1
34  19     1          4  0.000000  55.61      0       0       1
35  19     2          4  0.000000  55.82      0       0       1
36  19     3          4  0.018037  55.65      0       0       1
37  19     4          4  0.126259  81.17      1       0       1
38  20     1          4  0.000000  55.61      0       0       1
39  20     2          4  0.000000  55.82      0       0       1
40  20     3          4  0.018037  55.65      0       0       1
41  20     4          4  0.126259  81.17      1       0       1
42  21     1          4  0.000000  55.61      0       0       1
43  21     2          4  0.000000  55.82      0       0       1
44  21     3          4  0.018037  55.65      0       0       1
45  21     4          4  0.126259  81.17      1       0       1
46  22     1          4  0.000000  55.61      0       0       1
47  22     2          4  0.000000  55.82      0       0       1
48  22     3          4  0.018037  55.65      0       0       1
49  22     4          4  0.126259  81.17      1       0       1

0

In [11]:
kb2['time'] = kb2['week']
#start_time = time.time()
G2G_varying_MLE(time = 'week', status = 'status', indep = ['coupon', 'anyp'], data=kb2, subject="id") 
#elapsed_time = time.time() - start_time

    message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
    success: True
     status: 0
        fun: 2217.029718447927
          x: [ 5.000e-01  1.050e+00 -3.589e-04 -3.589e-04]
        nit: 2
        jac: [ 4.401e+03 -6.326e+02  1.520e+01  2.819e+04]
       nfev: 20
       njev: 4
   hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>
 par_stderr: [ 3.667e+01  1.153e+02  1.000e+00  1.390e+01]
  par_upper: [ 7.236e+01  2.271e+02  1.960e+00  2.724e+01]
  par_lower: [-7.136e+01 -2.250e+02 -1.960e+00 -2.725e+01]